version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: mukeshkr
      POSTGRES_PASSWORD: mukeshkr123
      POSTGRES_DB: jobapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - jobapp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: mukeshkr123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - jobapp-network

volumes:
  pgdata:

networks:
  jobapp-network:
    driver: bridge
